name: Greetings

on: [pull_request, issues]

jobs: |
  - greeting:
    container:
      image: ciscoappnetworking/kubectl_kind:latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
