name: Greetings

on: [pull_request, issues, push]

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    container: ciscoappnetworking/kubectl_kind:latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: 'master'

      - name: Pack the Helm Charts
        run: |
          pwd
          ls
          cd deployments
          mkdir docs
          mkdir -p helm_repo/docs/ucnf-kiknos

          helm package --destination helm_repo/docs helm/mysql-master
          helm package --destination helm_repo/docs helm/mysql-slave
          helm package --destination helm_repo/docs helm/nsm-addons
          helm package --destination helm_repo/docs/ucnf-kiknos helm/ucnf-kiknos/*
          helm package --destination helm_repo/docs helm/vl3
          helm package --destination helm_repo/docs helm/vl3_hello

          cd helm_repo
          helm repo index docs --url https://paulsterpu.github.io/nse-helm-repo/

          cd ../..

          mv deployments/helm_repo/docs/* docs
          rm -rf helm_repo
          rm -rf deployments/docs

          git config user.email "paulsterpu@gmail.com"
          git config user.name "paulsterpu"

          git add .
          git commit -m "Auto commit"
          git push

#      - name: Pushes to another repository
#        uses: cpina/github-action-push-to-another-repository@master
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#        with:
#          source-directory: 'nsm-nse/nsm-nse/helm_repo'
#          destination-github-username: 'paulsterpu'
#          destination-repository-name: 'nse-helm-repo'
#          user-email: paulsterpu@gmail.com
#        run: |
#          pwd
#          ls