name: Publish NSE Helm Charts

on:
  push:
#    branches: [ master ]

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    container: ciscoappnetworking/kubectl_kind:latest
    if: "context.repository_owner == cisco-app-networking"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: 'master'

      - name: Pack the Helm Charts
        run: |
          cd deployments
          mkdir -p helm_repo_tmp/docs/ucnf-kiknos

          helm package --destination helm_repo_tmp/docs helm/mysql-master
          helm package --destination helm_repo_tmp/docs helm/mysql-slave
          helm package --destination helm_repo_tmp/docs helm/nsm-addons
          helm package --destination helm_repo_tmp/docs/ucnf-kiknos helm/ucnf-kiknos/*
          helm package --destination helm_repo_tmp/docs helm/vl3
          helm package --destination helm_repo_tmp/docs helm/vl3_hello

          cd helm_repo_tmp
          helm repo index docs --url https://paulsterpu.github.io/nsm-nse/
          echo "NSE HELM REPO" > docs/index.html

      - name: Publish the Helm Charts
        run: |
          mkdir -p docs
          cp -R deployments/helm_repo_tmp/docs/* docs
          rm -rf deployments/helm_repo_tmp

          git config user.email "paulsterpu@gmail.com"
          git config user.name "paulsterpu"

          git add .
          git commit -m "Auto commit"
          git push

#      - name: Pushes to another repository
#        uses: cpina/github-action-push-to-another-repository@master
#        env:
#          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#        with:
#          source-directory: 'nsm-nse/nsm-nse/helm_repo_tmp'
#          destination-github-username: 'paulsterpu'
#          destination-repository-name: 'nse-helm-repo'
#          user-email: paulsterpu@gmail.com
#        run: |
#          pwd
#          ls